- .gitignore
- pymt/events/port.py
- pymt/framework/bmi_bridge.py
This PR collects a few changes to PyMT that @mcflugen and I came across in setting up the [wmt-testing](https://csdms.colorado.edu/wmt-testing/) instance.
> Minor fixes

- pymt/framework/bmi_bridge.py
- pymt/framework/bmi_docstring.py
- pymt/framework/bmi_metadata.py
- pymt/framework/bmi_plot.py
- pymt/framework/bmi_setup.py
- pymt/framework/bmi_ugrid.py
This pull request adds a `quick_plot` method, which creawtes a plot of a 2D BMI variable, to the `BmiCap`. `quick_plot` is not intended to create a particularly beautiful plot but, rather, just a quick and dirty one to peek at the state of a variable.
> Add quick_plot method

- pymt/framework/bmi_bridge.py
This pull request fixes the`update_until` method to run in the component's initialization folder (like, `initialize`, `update` and `finalize`).
> Run update_until in initdir.

- pymt/framework/bmi_setup.py
This pull request fixes a bug where a config file is sometimes not created in the correct location.
> Fix config file bug

- setup.py
Remove utility scripts in the `scripts` folder from the installation. In a future pull request, they should probably be removed completely.
> Do not install scripts.

- docs/conf.py
- docs/installation-check.rst
- docs/installation-environment.rst
- docs/installation-source.rst
- docs/installation-stable.rst
- docs/installation.rst
- docs/quickstart.rst
- pymt/plugin.py
This PR holds a set of changes to the pymt installation instructions based on discussions initiated at the user testing session on 2019-01-25.
> Update install instructions

- README.rst
- docs/index.rst
This is perhaps an aspirational PR. I added a major heading to the TOC to differentiate its contents from the API documentation. I also reordered the headings. And a minor change: I added links to CSDMS and BMI in the README.
> Modify TOC

- README.rst
- docs/index.rst
This PR contains minor changes to the text; e.g.,
* PyMT --> pymt
* Added NSF support statement to README
> Touch up main page and README

- docs/demos/quickstart.py
- docs/index.rst
- docs/quickstart.rst
This PR contains a fix to the Quickstart -- @sc0tts pointed out that the model in the example was advanced one step past its end time.
I've also made minor updates to the text, and included a script that runs all of the commands used in the Quickstart. (Note that this script should eventually be upgraded to a Jupyter Notebook and included in build tests.)
> Fix Quickstart example

- .travis.yml
- ci/requirements-lint.yml
- tests/printers/nc/test_ugrid.py
This pull request changes building our docs and running the linter to our CI tests.
> Add docs and lint to our CI tests

- docs/installation-check.rst
Hello,
In trying out the install guide, I found this small error (checked with the latest version in conda-forge)
Cheers,
Niels
> Small correction for install check

- AUTHORS.rst
- README.rst
- docs/examples.rst
- docs/index.rst
- docs/installation-environment.rst
- docs/installation.rst
- docs/readme.rst
This PR is a collection of minor updates to the docs since the v1.0 release.
> Minor updates to docs

- .codacy.yaml
- MANIFEST.in
- pymt/cfunits/__init__.py
- pymt/cfunits/etc/udunits/README
- pymt/cfunits/etc/udunits/udunits2-accepted.xml
- pymt/cfunits/etc/udunits/udunits2-accepted.xml.nonCF
- pymt/cfunits/etc/udunits/udunits2-base.xml
- pymt/cfunits/etc/udunits/udunits2-common.xml
- pymt/cfunits/etc/udunits/udunits2-common.xml.nonCF
- pymt/cfunits/etc/udunits/udunits2-derived.xml
- pymt/cfunits/etc/udunits/udunits2-derived.xml.nonCF
- pymt/cfunits/etc/udunits/udunits2-prefixes.xml
- pymt/cfunits/etc/udunits/udunits2.xml
- pymt/cfunits/units.py
- pymt/cfunits/units.py.orig
- pymt/cfunits/units.py.rej
- pymt/framework/bmi_bridge.py
- pymt/units.py
- setup.cfg
This pull request adds a version of *cfunits* within the *pymt* package. This is definitely not ideal but it's the easiest (and quickest) way to incorporate the changes required to get *cfunits* working on Windows.
> Include cfunits within pymt package

- docs/environment.yml
- pymt/cfunits/__init__.py
- pymt/cfunits/units.py
- pymt/framework/bmi_bridge.py
- pymt/framework/bmi_docstring.py
- pymt/framework/bmi_plot.py
- pymt/framework/bmi_ugrid.py
- pymt/grids/__init__.py
- pymt/mappers/__init__.py
- pymt/units.py
- tests/framework/test_setup.py
- tests/test_models.py
Wrap BMI models with a "sensible" BMI and deprecate the insensible BMI methods. In Python methods like *get_var_grid* should just be *var_grid*.
> Add sensible BMI

- docs/environment.yml
- docs/examples.rst
- docs/install.rst
- docs/quickstart.rst
- notebooks/cem.ipynb
- notebooks/cem_and_waves.ipynb
- notebooks/child.ipynb
- notebooks/frost_number.ipynb
- notebooks/hydrotrend.ipynb
- notebooks/ku.ipynb
- notebooks/sedflux3d.ipynb
- notebooks/sedflux3d_and_child.ipynb
- notebooks/subside.ipynb
- pymt/cfunits/units.py
This PR adds links to the Help Desk to the 
* Quickstart,
* Installation, and
* Examples
pages in the documentation, inviting users to contact CSDMS through the Help Desk if they run into any problems.
cc: @iovereem
> Add additional links to the Help Desk

- notebooks/README.md
- notebooks/welcome.ipynb
Add a readme file under notebooks folder
Update the welcome.ipynb
> Tian notebook readme

- notebooks/README.md
- tests/printers/nc/test_nc.py
In this PR, I updated the links used for authorizing a user on the CSDMS JupyterHub. I also did some light editing on the text.
> Update links for Hub authorization

- .travis.yml
- README.rst
- docs/_templates/links.html
- docs/glossary.rst
- docs/index.rst
In this PR, I've added text about the CSDMS Workbench to the docs (index, sidebar, and glossary) and the README.
> Add Workbench text

- .github/workflows/docs.yml
- docs/conf.py
This pull request adds a workflow that tests the building of *pymt*'s docs.
> Add GitHub Actions workflow to build the docs

- CHANGELOG.rst
- setup.cfg
This PR attempts to fix the successful, but 0%, coverage score reported by Coveralls through the [coveralls-python](https://github.com/marketplace/actions/coveralls-python) Action.
> Use relative_files configuration for coveralls

- CHANGELOG.rst
- news/.gitignore
- news/145.misc
- news/146.misc
- news/150.bugfix
- news/153.bugfix
- news/154.misc
- news/155.misc
- pyproject.toml
This pull request setup *towncrier* to manage the changelog.
> Setup towncrier
