csdms/pymt

conda-recipe/meta.yaml
pymt/framework/bmi_docstring.py
pymt/framework/tests/test_bmi_docstring.py
requirements.txt

The pull request uses jinja2 templates to generate docstrings for BMI-wrapped PyMT components.

Use jinja templates

---

pymt/framework/bmi_bridge.py
pymt/framework/tests/test_bmi_time_units.py

The pull request adds a setter method for `time_units`. This allows the user to set the time units for a component. For example,
```python
>>> bmi.time_units
'h'
>>> bmi.get_current_time()
72
>>> bmi.time_units = 'min'
>>> bmi.get_current_time()
3
```

Add setter for time units

---

pymt/framework/bmi_docstring.py
pymt/framework/bmi_metadata.py
pymt/framework/tests/test_bmi_docstring.py

This pull request adds a "cite_as" section to a component's *info* section of its BMI metadata. It also adds a "Cite as" section to its docstring that just lists the citations from the metadata file.

Add cite as metadata

---

CHANGELOG.md
scripts/make_changelog.py

This pull request both adds a change log and a script to auto-generate a new change log based on `git log` that tries to adhere to the [Keep a Changelog](http://keepachangelog.com/) format.
The change log is composed of one-line commit messages from all merges into `master` and split into sections that depend on the contents of the message. For instance, if the message starts with `Add`, the commit will be put into the `Added` section.

Add change log

---

pymt/framework/bmi_bridge.py

This pull requests add a new method, `initdir`, that refers to the folder that contains the initialization files. In addition, each of the IRF methods, `initialize`, `update`, and `finalize` are run in this folder.

Run IRF methods within the initialization folder

---

pymt/framework/bmi_bridge.py
pymt/framework/bmi_setup.py

This PR fixes a bug where the relative path of the `initdir` was being used in `initialize`. The `setup` method now also returns the absolute path to the initdir (regardless what was passed as the `dir` keyword).

Fix absolute path for initdir

---

pymt/framework/bmi_docstring.py
pymt/framework/bmi_metadata.py
pymt/framework/tests/test_bmi_docstring.py

This pull request reads a model's `info.yaml` file and parses the `author` field as either a string or a list of strings to represent multiple authors. The authors are listed in the docstring as one per line.

Allow multiple authors of components

---

pymt/framework/bmi_bridge.py
pymt/framework/bmi_mapper.py
pymt/framework/bmi_plot.py
pymt/framework/bmi_ugrid.py

This pull requests adds grid mappers to PyMT components by introducing a `mapfrom` keyword to a component's `set_value` method. If the `mapfrom` keyword is used, instead of getting values from an array, the values will be retrieved from another component (through its `get_value` method).
For example:
```python
>>> model.set_value('x', [1,2,3,4]) # Set values from an array
>>> model.set_value('x', mapfrom=another_model) # Set values from another component
>>> model.set_value('x', mapfrom=('y', another_model)) # Set values with another name from another component
```

Add grid mapper

---

.travis.yml
pymt/__init__.py
pymt/printers/nc/tests/test_ugrid_read.py

In numpy 1.14, an improvement was made which attempts to remove extra spaces from printed floats (see [release notes](https://github.com/numpy/numpy/blob/master/doc/release/1.14.0-notes.rst#many-changes-to-array-printing-disableable-with-the-new-legacy-printing-mode)). This wreaked havoc with docstring tests. Using `numpy.set_printoptions(legacy='1.13')` disables this new behavior.
Interestingly, for builds on Travis, the Miniconda3 installer caused problems when trying to install Python 2.7. This should work. Using the Miniconda2 installer solved the problem. We should keep an eye on this, though, as 2.7 is phased out.
Also, an unrelated problem -- last week OIT made csdms.colorado.edu accessible only by HTTPS, which caused the URL for the CSDMS THREDDS server used in tests to fail.

Allow legacy docstrings with numpy 1.14

---

pymt/__init__.py
pymt/framework/bmi_bridge.py
pymt/framework/bmi_ugrid.py
pymt/framework/tests/test_bmi_time_units.py
pymt/plugin.py
pymt/utils/decorators.py

This pull request adds a new method of discovering pymt plugins. Plugins are still found in the old way (that is, looking for a `csdms` package and loading BMI classes from there) and, as before, can be accessed through `pymt.components`. The new-style plugins are contained in `pymt.plugins`. The old-style plugins are also here but may be removed in the future.
BMI plugins are now registered in the component's setup.py file as a `pymt.plugin` entry point. The `model_metadata` package (as of version 0.3) provides some convenience functions for registering and installing these sorts of plugins.

Add new-style plugins

---

pymt/framework/bmi_ugrid.py

This pull requests adds support for a "grid" that is a vector but without any spatial component. This is kind of like *"scalar"* grid but a vector rather than a single number. The grid type, as returned by `get_grid_type`, is *"vector"*.

Represent vector data as an xarray Dataset.

---

pymt/component/tests/conftest.py
pymt/component/tests/test_map_component.py
pymt/component/tests/test_model.py
pymt/component/tests/test_one_component.py
pymt/component/tests/test_recursive.py
pymt/component/tests/test_two_components.py
pymt/framework/bmi_ugrid.py
pymt/framework/services.py
pymt/portprinter/tests/conftest.py
pymt/portprinter/tests/test_port_printer_queue.py
pymt/portprinter/tests/test_vtk_port_printer.py

This pull request fixes errors related to some pytest fixtures. The problem was that I had two `conftest.py` files, each of which defined a fixture called `setup`. One `setup` was being overridden by the other, which caused the wrong fixture to be run for some tests. I've renamed the fixtures to have more descriptive (and different!) names.

Fix pytest fixture errors

---

pymt/component/component.py
pymt/component/model.py
pymt/component/tests/test_grid_mixin.py
pymt/component/tests/test_map_component.py
pymt/component/tests/test_one_component.py
pymt/component/tests/test_recursive.py
pymt/component/tests/test_two_components.py
pymt/components.py
pymt/plugin.py

This pull request changes which components are put into the `pymt.components` module. Previously "old-style" components were placed in the `pymt.components` module and "new-style" components were placed in the `pymt.plugins` object. Now all components are loaded into both places. So,
```python
import pymt.components
hydrotrend = pymt.components.Hydrotrend()
```
and
```python
from pymt import plugins
hydrotrend = plugins.Hydrotrend()
```
now do the same thing.

Import plugins into components module

---

setup.py

Change `setup.py` so that only `pymt` and `cmt` are installed as part of the package. Previously, the `tests` folder was also being installed.

Fix find_packages in setup.py

---

docs/installation-check.rst
docs/installation-environment.rst
docs/usage.rst

This PR updates the Usage section of the docs to give an overview of the minimum set of functions needed to work with pymt.
Note that all pymt functions and properties should be described in this section, but are not, yet. This is #59.

Write Usage section

---

docs/demos/hydrotrend.ipynb

Small changes to hydrotrend.ipynb to give users a command -- using curl -- to download a local copy of the Hydrotrend notebook.  
Also, clean up the notebook by removing a couple of duplicated informational cells.

hydrotrend.ipynb tweaks: add curl command and remove duplicate cells

---

docs/demos/ku.ipynb

Small changes to ku.ipynb to give users a command -- using curl -- to download a local copy of the Hydrotrend notebook.  
Update the calls to the model to refer to pymt.models() instead of pymt.plugins()

Update ku.ipynb: add curl command and change imports to pymt.models

---

.gitignore
docs/examples.rst
docs/index.rst

Added a Help section to the bottom of the main page. It lists the CSDMS Support email, and points experienced users to log issues on the *pymt* GitHub page.
Also listed the operating systems that each example should work on.

Add help instructions

---

pymt/events/port.py
pymt/framework/bmi_setup.py
tests/framework/test_setup.py

This pull request fixes an error caused when a model's info metadata contains *authors* key (rather than *author* - singular). For now, anyway, I've changed it so that both are valid keys (look for *author* and then *authors*). The author list is now always a tuple.

Fix multiple authors error

---

pymt/framework/bmi_metadata.py
pymt/printers/nc/ugrid.py
tests/framework/test_setup.py

Fix an issue where the `.METADATA` attribute of a *BMI* class wasn't working properly. If the path was provided as an absolute path, the path to the *pymt* module was prepended to it rather that just using the provided path.

Fix METADATA attribute

---

pymt/framework/bmi_setup.py

This pull request fixes a error when loading BMI classes that use the `METADATA` attribute to indicate where their model metadata is located. The metadata was being searched for based on the name of the model. Instead the class of the model should be used so that the `METADATA` attribute can be queried.

Fix finding metadata from BMI class

---

pymt/__init__.py

This fixes an issue on Windows where the units database could not be found (`udunits2.xml`). This resulted as an assertion error when importing *cfunits* from within *pymt*,
```python
>>> import cfunits
Traceback (most recent call last):
...
assert(0 == _ut_unmap_symbol_to_unit(_ut_system, _c_char_p(b'Sv'), _UT_ASCII))
```
The issue is that *udunits2* library can not correctly find `udunits2.xml` in the default location. On Windows anyway. To fix this, I set the `UDUNITS_XML_PATH` environment variable in `pymt/__init__.py` to point to the path of `udunits2.xml` within the *cfunits* package. I do this for all platforms, not just Windows but I think that should be fine.

Fix cfunits import error on Windows

---

appveyor.yml
pymt/framework/bmi_ugrid.py
tests/framework/test_bmi_ugrid.py

In this PR, I attempted to factor out repeated code in the *pymt.framework.bmi_ugrid* module, while rewriting the set of functions in the module as classes. I also added the ability to handle the `structured_quadrilateral` BMI grid type, which fixes #88. I included unit tests for each new class.

Refactor pymt.framework.bmi_ugrid module and add tests

---

pymt/framework/bmi_ugrid.py
tests/framework/test_bmi_ugrid.py

This PR adds support for the BMI [rectilinear](https://bmi.readthedocs.io/en/latest/bmi.grid_funcs.html#rectilinear) grid type. The implementation is based on landlab's RectilinearGraph class. Unit tests are included.

Add rectilinear grid type

---

README.rst

This pull request fixes some broken links to the docs that were in the `README`.

Fix broken links to the docs in README

---

pymt/framework/bmi_bridge.py

For a rectilinear grid, these functions should return, respectively, a vector of length number of columns, number of rows, and number of zlevels, not a vector of length node_count. The behavior of these functions is unchanged for other grid types.
See more on this at https://github.com/csdms/bmi/issues/65.

Change behavior of grid_x, y, and z for rectilinear grids

---

pymt/cfunits/units.py
setup.py

This pull request installs the *pymt*-embedded *cfunits* xml data files with the package. Without these data files, *cfunits* would report an error about Sverdrups (Sv).
```python
Traceback (most recent call last):
...
assert 0 == _ut_unmap_symbol_to_unit(_ut_system, _c_char_p(b"Sv"), _UT_ASCII)
AssertionError
```
I've also fixed on *SyntaxWarnings* with *cfunits* that warned about using `is` with literal comparisons rather than `==`.

Install cfunits xml data

---

CHANGELOG.rst
pymt/framework/bmi_plot.py

This pull request fixes an issue in *quickplot* when it's given an *unstructured* mesh. Previously, the grid type, as returned by a BMI, had to be *unstructured_triangular* but that's no longer a valid grid type. Now, *quickplot* understands *unstructured* but then checks to ensure that all faces have exactly 3 edges. If they don't, an exception is raised.

Check if unstructured mesh has only triangular faces

---

CITATION.cff

I've added a citation file for the *pymt* in the [Citation File Format](https://citation-file-format.github.io/).

Add citation file for pymt

---

requirements-testing.txt
tests/portprinter/test_port_printer_queue.py
tests/printers/nc/test_database.py
tests/printers/nc/test_nc.py

This pull request fixes an error we began seeing with, I think, newer versions of *xarray* when running the netcdf printer tests. The error was only on Windows and indicated that *xarray* *"did not find a match in any of xarray's currently installed IO backends"*. For whatever reason, *h5netcdf* is not installed on Windows but that is the backend engine needed to read some of the test netcdf files. 
I've added *h5netcdf* as an explicit requirement in *requirements-testing.txt* and explicitly set the *engine* to *h5netcdf* when calling `xr.open_dataset`.

Fix missing netcdf engine error on Windows

---

pymt/grids/structured.py
pymt/grids/unstructured.py
pymt/grids/utils.py
pymt/mappers/celltopoint.py
pymt/mappers/pointtocell.py
pymt/services/constant/constant.py
tests/mappers/test_mapper.py

This fixes a deprecation from [numpy 1.20.0](https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated).

fix: numpy aliases of builtin types is deprecated

---

environment-docs.yml

This PR includes a minor change: as described [here](https://stackoverflow.com/a/59056234) and [here](https://stackoverflow.com/a/68586065), valid syntax for the `file:` URI has changed in `pip`, and the current form raises an exception. Removed the `file:` URI from the environment file.

Drop file: URI from pip install

---

docs/examples.rst
docs/glossary.rst
docs/quickstart.rst

The Examples section of the documentation includes a list of example notebooks with links to run them on Binder, but it doesn't have links to the notebooks themselves for viewing. This PR adds those links in a suboptimal, but (I think) satisfactory, manner--linking to GitHub, where each notebook is rendered for viewing.
This fixes #102. (From 2019! I've been meaning to fix this for a while.)

Add links to notebooks

---

environment.yml

As reported by @iovereem, some of the notebooks are not running on Binder. I've updated the *environment.yml* file to include additional dependencies and removed the *pymt* version requirement.

Update the environment.yml file for use with Binder

---

deprecated/component_info.py
deprecated/ordered_task_status.py
deprecated/portprinter/tests/test_bov_port_printer.py
deprecated/portprinter/tests/test_vtk_port_printer.py
deprecated/printers/vtk/vtkxml.py
deprecated/printers/vtk/vtu.py
deprecated/task_status.py
deprecated/test_component_info.py
deprecated/tests/test_task_status.py
deprecated/utils/verbose.py
notebooks/child.ipynb
requirements.txt

This is a small follow-up on #159 to remove other uses of `six`.

Remove other uses of six dependency

---

.github/workflows/test-notebooks.yml
.github/workflows/test.yml
requirements.txt

This pull request updates *pymt*'s continuous integraion. Bumped some of the actions, bumped Python to 3.10 for the tests, updated the requirements.
As with #170, these commits were cherry picked from #169.

Update continuous integration
